const ActionTypes = {
	// Auth Action types 
	START_LOGIN_SPOTIFY: 'START_LOGIN_SPOTIFY',
	LOGIN_SPOTIFY: 'LOGGED_IN_SPOTIFY',
	LOGGED_IN_FACEBOOK: 'LOGGED_IN_FACEBOOK',
	USER_REGISTERED: 'USER_REGISTERED',

	// User Action types
	SET_USER_INFO: 'SET_USER_INFO',
	REQUEST_ADD_FOLLOWER: 'REQUEST_ADD_FOLLOWER',
	DONE_ADD_FOLLOWER: 'DONE_ADD_FOLLOWER',
	ADD_FOLLOWER: 'ADD_FOLLOWER',

	REQUEST_REMOVE_FOLLOWER: 'REQUEST_REMOVE_FOLLOWER',
	DONE_REMOVE_FOLLOWER: 'DONE_REMOVE_FOLLOWER',
	REMOVE_FOLLOWER: 'REMOVE_FOLLOWER',
	SET_FOLLOWERS: 'SET_FOLLOWER',

	REQUEST_ADD_FOLLOWING: 'REQUEST_ADD_FOLLWING',
	DONE_ADD_FOLLOWING: 'DONE_ADD_FOLLWING',
	ADD_FOLLOWING: 'ADD_FOLLWING',
	SET_FOLLOWING: 'SET_FOLLOWING',

	REQUEST_REMOVE_FOLLOWING: 'REQUEST_REMOVE_FOLLOWING',
	DONE_REMOVE_FOLLOWING: 'DONE_REMOVE_FOLLOWING',
	REMOVE_FOLLOWING: 'REMOVE_FOLLOWING',

	UPDATE_CURRENT_PLAYBACK: 'UPDATE_CURRENT_PLAYBACK',
	API_ERROR: 'API_ERROR'
};

export default ActionTypes;