const ActionTypes = {
    // Auth Action types 
    START_LOGIN_SPOTIFY: 'START_LOGIN_SPOTIFY',
    LOGIN_SPOTIFY: 'LOGIN_SPOTIFY',
    LOGIN_FACEBOOK: 'LOGIN_FACEBOOK',

    // User Action types
    REQUEST_ADD_FOLLOWER: 'REQUEST_ADD_FOLLOWER',
    DONE_ADD_FOLLOWER: 'DONE_ADD_FOLLOWER',
    ADD_FOLLOWER: 'ADD_FOLLOWER',

    REQUEST_REMOVE_FOLLOWER: 'REQUEST_REMOVE_FOLLOWER',
    DONE_REMOVE_FOLLOWER: 'DONE_REMOVE_FOLLOWER',
    REMOVE_FOLLOWER: 'REMOVE_FOLLOWER',

    REQUEST_ADD_FOLLOWING: 'REQUEST_ADD_FOLLWING',
    DONE_ADD_FOLLOWING: 'DONE_ADD_FOLLWING',
    ADD_FOLLOWING: 'ADD_FOLLWING',

    REQUEST_REMOVE_FOLLOWING: 'REQUEST_REMOVE_FOLLOWING',
    DONE_REMOVE_FOLLOWING: 'DONE_REMOVE_FOLLOWING',
    REMOVE_FOLLOWING: 'REMOVE_FOLLOWING',

    UPDATE_CURRENT_TRACK: 'UPDATE_CURRENT_TRACK',
    UPDATE_RECENTS: 'UPDATE_RECENTS',
    API_ERROR: 'API_ERROR'
};

export default ActionTypes;